//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipalities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBNew
    {
        public int FBNewsId { get; set; }
        public Nullable<int> MunId { get; set; }
        public string FBname { get; set; }
        public string FBmessage { get; set; }
        public string FBpicture { get; set; }
        public string FBcreated { get; set; }
        public string FBlink { get; set; }
        public Nullable<int> FBmonth { get; set; }
        public Nullable<int> FByear { get; set; }
        public Nullable<int> FBday { get; set; }
    }
}
