//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipalities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class municipalitiesEntities : DbContext
    {
        public municipalitiesEntities()
            : base("name=municipalitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FBInfo> FBInfoes { get; set; }
        public virtual DbSet<FBNew> FBNews { get; set; }
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<TwitterInfo> TwitterInfoes { get; set; }
        public virtual DbSet<TwitterNew> TwitterNews { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<YTInfo> YTInfoes { get; set; }
        public virtual DbSet<YTNew> YTNews { get; set; }
    }
}
