//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipalities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality
    {
        public int MunId { get; set; }
        public string Name { get; set; }
        public string FBId { get; set; }
        public string TwitterID { get; set; }
        public string YTId { get; set; }
        public Nullable<int> NumFBAct { get; set; }
        public Nullable<int> NumTwitterAct { get; set; }
        public Nullable<int> NumYTAct { get; set; }
    }
}
