//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipalities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterNew
    {
        public int TNewsId { get; set; }
        public Nullable<int> MunId { get; set; }
        public string TText { get; set; }
        public string TCreated { get; set; }
        public string TLink { get; set; }
        public string TMedia { get; set; }
        public Nullable<int> TMonth { get; set; }
        public Nullable<int> TYear { get; set; }
        public Nullable<int> TDay { get; set; }
    }
}
