//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipalities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterInfo
    {
        public int TInfoId { get; set; }
        public Nullable<int> MunId { get; set; }
        public string Tdescription { get; set; }
        public string TFollowers { get; set; }
        public string TFollowing { get; set; }
        public string TProfileCreated { get; set; }
        public string TNumTweers { get; set; }
        public string TProfilePic { get; set; }
    }
}
