//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipalities
{
    using System;
    using System.Collections.Generic;
    
    public partial class YTNew
    {
        public int YTNewsId { get; set; }
        public Nullable<int> MunId { get; set; }
        public string YTTitle { get; set; }
        public string YTVideo { get; set; }
        public Nullable<int> YTDay { get; set; }
        public Nullable<int> YTMonth { get; set; }
        public Nullable<int> YTYear { get; set; }
    }
}
